
<footer class="col s12 valign-wrapper">
    <h6 class="center-container">
        <?=$_SERVER['REMOTE_ADDR']?> <br>
        <?=_::n(microtime(1)-$_SERVER['REQUEST_TIME_FLOAT'], 3 ) . ' s'?> —
        <?=_::n(memory_get_usage()/1048576, 2) . ' MB'?>
    </h6>
</footer>

<div class="scroll-buttons hide">
    <a class="btn-floating scroll-top">
        <i class="material-icons">keyboard_arrow_up</i>
    </a>
</div>
