
<header class="col s12 center-align">
    <ul class="collection">
        <li class="collection-item logo">
            <a href="/blog/">
            	<img alt="[LOGO KUMBIAPHP]" class="responsive-img" src="/img/kumbiaphp.svg">
            	<p>Web & app MVC PHP framework</p>
            </a>
        </li>
        <li class="collection-item m0 l0 right-align">
        	<a class="btn-floating btn-large blue-bg" data-toggle-aside="aside.blog"><i class="material-icons">menu</i></a>
        </li>
    </ul>
</header>
