<?php
$time = strtotime($post->post_date);
$post_date = date('Y/m/d', $time); 
?>
<div class="col s12 m7 l8">
    <ul class="collection">
        <li class="collection-item rowxsxs">
            <h1><?=$post->post_title?></h1>
            <div class="col s6 m6 l3 valign-wrapper">
                <i class="material-icons">date_range</i> &nbsp;
                <?=strftime('%e %B, %Y', $time)?>
            </div>
            <div class="col s6 m6 l3 valign-wrapper">
                <?=Html::gravatar('distrotuz@gmail.com')?> &nbsp;
                by &nbsp; <a href="/blog/author/<?=$post->user_nicename?>/"><?=$post->display_name?></a>
            </div>
            <div class="clearfix l0"></div>
            <hr class="mv15 l0">
            <div class="col s6 m6 l3 valign-wrapper">
                <i class="material-icons">comment</i> &nbsp;
                comments
            </div>
            <div class="col s6 m6 l3 valign-wrapper">
                <a href="//www.facebook.com/sharer/sharer.php?u=https://<?=$_SERVER['HTTP_HOST']?>/blog/<?="$post_date/$post->post_name"?>"
                    target="_blank">
                    <img src="/img/icon-facebook.svg" width="32">
                </a> &nbsp; &nbsp; &nbsp; 
                <a href="//twitter.com/home?status=<?=urlencode($post->post_title)?>%20—%20//<?=$_SERVER['HTTP_HOST']?>/blog/<?="$post_date/$post->post_name"?>"
                    target="_blank">
                    <img src="/img/icon-twitter.svg" width="32">
                </a>
            </div>
            <div class="clearfix"></div>
        </li>
        <li class="collection-item">
            <div class="flow-text"><?=$post->post_content?></div>
        </li>
        <li class="collection-item">
            <?php foreach ($tags as $o) : ?>
                <a href="/blog/tag/<?=$o->slug?>/">
                    <div class="chip"><?=$o->name?></div>
                </a>
            <?php endforeach; ?>
        </li>
    </ul>
</div>
