
<div class="col s12 m7 l8">
    <?php if ( ! empty($main_header) ) : ?>
        <ul class="collection">
            <li class="collection-item">
                <h1 class="center-align black-text">
                    <small><?=$header_type?></small>
                    <?=$main_header?>
                </h1>
                <?php if ( ! empty($author) ) : ?>
                    <div class="col s6 right-align">
                        <em><?=$posts[0]->description;?></em>
                    </div>
                    <div class="col s6">
                        <?=Html::gravatar($posts[0]->user_email, 'gravatar', 64)?>
                        <a class="inline ma10" href="<?=$posts[0]->user_url;?>" target="_blank"><?=$posts[0]->user_url;?></a>
                    </div>
                    <div class="clearfix"></div>
                <?php endif; ?>
            </li>
        </ul>
    <?php endif;
    foreach ($posts as $o) :
        $time = strtotime($o->post_date);
        $post_date = date('Y/m/d', $time); ?>
        <ul class="collection posts">
            <li class="collection-item rowxsxs">
                <h2>
                    <a href="/blog/<?="$post_date/$o->post_name"?>">
                        <?=($action_name == 'search')
                            ? str_ireplace($main_header,
                                '<span style="background:yellow">' . $main_header . '</span>',
                                $o->post_title)
                            : $o->post_title?>
                    </a>
                </h2>
                <div class="col s6 m6 l3 valign-wrapper">
                    <i class="material-icons">date_range</i> &nbsp;
                    <?=strftime('%e %B, %Y', $time)?>
                </div>
                <div class="col s6 m6 l3 valign-wrapper">
                    <?=Html::gravatar($o->user_email)?> &nbsp; &nbsp;
                    <a href="/blog/author/<?=$o->user_nicename?>/"><?=$o->display_name?></a>
                </div>
                <div class="clearfix l0"></div>
                <hr class="mv15 l0">
                <div class="col s6 m6 l3 valign-wrapper">
                    <i class="material-icons">comment</i> &nbsp;
                    <a href="/blog/<?="$post_date/$o->post_name#comments"?>">
                    	<?=empty($n_comments[$o->ID])?0:$n_comments[$o->ID]?>
                    	Comments
                    </a>
                </div>
                <div class="col s6 m6 l3 valign-wrapper">
                    <a href="//www.facebook.com/sharer/sharer.php?u=https://<?=$_SERVER['HTTP_HOST']?>/blog/<?="$post_date/$o->post_name"?>"
                        target="_blank">
                        <img src="/img/icon-facebook.svg" width="32">
                    </a> &nbsp; &nbsp; &nbsp; 
                    <a href="//twitter.com/home?status=<?=urlencode($o->post_title)?>%20—%20//<?=$_SERVER['HTTP_HOST']?>/blog/<?="$post_date/$o->post_name"?>"
                        target="_blank">
                        <img src="/img/icon-twitter.svg" width="32">
                    </a>
                </div>
                <div class="clearfix"></div>
            </li>
            <li class="collection-item">
                <div>
                    <?=($action_name == 'search')
                        ? str_ireplace( $main_header,
                            '<span style="background:yellow">' . $main_header . '</span>',
                            _str::firstP($o->post_content) )
                        : _str::firstP($o->post_content)?>
                    </div>
                <hr>
                <p class="center-align"><a href="/blog/<?="$post_date/$o->post_name"?>">— CONTINUAR LEYENDO —</a></p>
            </li>
        </ul>
    <?php endforeach; ?>
</div>
